carts/urls.py
from django.urls import path
from carts.views import CartView, cart_add, cart_remove, cart_update

app_name = 'carts'

urlpatterns = [
    path('', CartView.as_view(), name='index'),
    path('add/', cart_add, name='add'),
    path('update/', cart_update, name='update'),
    path('remove/', cart_remove, name='remove'),
]

seedlings/urls.py
from django.urls import path
from seedlings.views import SeedlingList

urlpatterns = (
    path('', SeedlingList.as_view(), name='list'),
)

viride/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from django.views.defaults import page_not_found
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from catalog.sitemap import CatalogSitemap
from catalog.views import CatalogItemList
from conifers.sitemap import ConiferProductSitemap
from contacts.sitemap import ContactsSitemap
from contacts.views import contacts
from deciduous.sitemap import DecProductSitemap
from favorites.views import favorites
from fruits.sitemap import FruitProductSitemap
from index.sitemap import IndexSitemap
from index.views import index
from other.sitemap import OtherProductSitemap
from other.views import (
    BookProductDetail, BookProductList, RelatedProductDetail, RelatedProductList)
from perennials.sitemap import PerProductSitemap
from pricelist.sitemap import PriceListSitemap
from pricelist.view import price_list
from profiles.allauth.views import PersistLogoutView, RedirectedPasswordChangeView
from roses.sitemap import RoseProductSitemap
from sales.sitemap import SaleSitemap
from sales.views import sale
from search.views import SearchView


admin.site.site_header = admin.site.site_title = 'Питомник растений «Вириде»'


#--

sitemaps = {
    'index': IndexSitemap,
    'catalog': CatalogSitemap,
    'sale': SaleSitemap,
    'contacts': ContactsSitemap,
    'roses': RoseProductSitemap,
    'conifers': ConiferProductSitemap,
    'decs': DecProductSitemap,
    'fruits': FruitProductSitemap,
    'pers': PerProductSitemap,
    'other': OtherProductSitemap,
    # 'pricelist': PriceListSitemap,
}

# --

urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/logout/', auth_views.LogoutView.as_view(next_page='/admin/login'), name='logout'),
    path('admin/', admin.site.urls),
    path("accounts/email/", page_not_found,
         kwargs={"exception": Exception("Page not Found")},),
    path('accounts/password/change/', RedirectedPasswordChangeView.as_view(),
         name="account_change_password"),

    # path('login/', PersistLoginView.as_view(), name='account_login'),
    path('accounts/logout/', PersistLogoutView.as_view(), name='account_logout'),

    # path('account/login/', RedirectView.as_view(permanent=True, url='/accounts/login/')), #seems allauth bug
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),

    path('', index, name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('sale/', sale, name='sale_list'),
    path('price-list/', price_list, name='price_list_detail'),
    path('contacts/', contacts, name='contacts'),

    path('catalog/', CatalogItemList.as_view(), name="catalog_item_list"),
    # path('catalog/', TemplateView.as_view(
    #     template_name="catalog/index.html"), name="catalog_template"),

    path('catalog/conifers/', include(('conifers.urls','conifers'), namespace='conifers')),
    path('catalog/deciduous/',
         include(('deciduous.urls', 'deciduous'), namespace='decs')),
    path('catalog/fruits/', include(('fruits.urls', 'fruits'), namespace='fruits')),
    path('catalog/perennials/',
         include(('perennials.urls', 'perennials'), namespace='pers')),

    path('catalog/seedlings/',
         include(('seedlings.urls', 'seedlings'), namespace='seedlings')),
    
    path('catalog/roses/', include(('roses.urls', 'roses'), namespace='roses')),

    path('catalog/books/',
         BookProductList.as_view(), name='book_list'),
    path('catalog/books/<slug:slug>/',
         BookProductDetail.as_view(), name='book_detail'),

    path('catalog/related/',
         RelatedProductList.as_view(), name='related_list'),
    path('catalog/related/<slug:slug>/',
         RelatedProductDetail.as_view(), name='related_detail'),

    path('favorites/', favorites, name='favorites'),

    path('cart/', include(('carts.urls', 'carts'), namespace='carts')),
    path('order/', include(('orders.urls', 'orders'), namespace='orders')),

    path('privacy-policy/', TemplateView.as_view(
        template_name="privacy-policy/index.html"), name="p-p_template"),

    path('sitemap.xml', cache_page(86400, cache='sitemap')(sitemap), {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

#--


def handler400(request, exception, template_name='errors/400.html'):
    response = render(request, template_name)
    response.status_code = 400
    return response


def handler403(request, exception, template_name='errors/403.html'):
    response = render(request, template_name)
    response.status_code = 403
    return response


def handler404(request, exception, template_name='errors/404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response


def handler500(request, template_name='errors/500.html'):
    response = render(request, template_name)
    response.status_code = 500
    return response

# --

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += [
        path('400/', TemplateView.as_view(template_name="errors/400.html")),
        path('403/', TemplateView.as_view(template_name="errors/403.html")),
        path('404/', TemplateView.as_view(template_name="errors/404.html")),
        path('500/', TemplateView.as_view(template_name="errors/500.html")),
    ]
        
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(r'/favicon.ico', document_root='static/favicon.ico')

seedlings/models.py
from urllib.parse import urlsplit, urlunsplit
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField
from common.managers import IsVisibleManager
from images.models import get_image_path
from plants.models import PlantDivision


class Seedling(models.Model):
    is_visible = models.BooleanField('показывать?', default=1, db_index=True)

    name = models.CharField('название', max_length=80, unique=True)

    division = models.ForeignKey(
        PlantDivision, verbose_name='отдел', on_delete=models.CASCADE,
        help_text='Классификация растений: Отдел. Пример: Хвойные.',)

    url = models.CharField(
        'url-адрес', max_length=250,
        help_text='Url-адрес страницы с ценами. Например: https://viride.spb.ru/catalog/conifers/el-kanadskaya-alberta-globe/')

    image_path = ThumbnailerImageField(
        'Путь к картинке',
        max_length=200,
        upload_to=get_image_path,
        resize_source={'size': (800, 800), 'crop': 'scale'}
    )

    image_title = models.CharField(
        'аттрибут title картинки', max_length=200, blank=True,)

    upload_to_dir = 'seedlings'

    date_shooting = models.DateField('дата съемки')

    objects = models.Manager()

    is_visible_objects = IsVisibleManager()

    def __str__(self):
        return str(self.name)

    def clean(self):
        url = urlsplit(self.url)
        self.url = urlunsplit(url._replace(scheme="")._replace(netloc=""))

    class Meta:
        ordering = ('name', )
        unique_together = (('name', 'division'),)
        verbose_name = 'саженцы'
        verbose_name_plural = 'саженцы'

seedlings/forms.py
from django import forms
from images.widgets import ImageAdminWidget
from seedlings.models import Seedling


class SeedlingAdminForm(forms.ModelForm):
    class Meta:
        model = Seedling
        widgets = {
            'image_path': ImageAdminWidget(),
        }
        exclude = []


seedlings/views.py
from django.views.generic import ListView
from common.mixins import PerPageMixin, PlantDivisionFilterMixin
from pure_pagination.mixins import PaginationMixin
from seedlings.models import Seedling


class SeedlingList(PaginationMixin,
                        #  ConiferFilterFormMixin,
                         PerPageMixin,
                        #  PlantSpeciesFilterMixin, 
                        #  PlantGenusFilterMixin,
                         PlantDivisionFilterMixin,
                         ListView):
    model = Seedling
    template_name = 'seedlings/list.html'
    queryset = Seedling.is_visible_objects.all()

templates/seedlings/list.html
{% extends 'main.html' %}
{% load thumbnail django_bootstrap_breadcrumbs static %}

{% block head %}
  <title>Саженцы | Вириде - питомник растений</title>
  <meta property="og:title" content="Саженцы | Viride - питомник садово-парковых растений">
  <meta name="description" content="Саженцы">
  <meta property="og:description" content="Саженцы">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ host }}{% url 'seedlings:list' %}">
{% endblock %}

{% block name %}
  Саженцы
{% endblock %}

{% block breadcrumb %}
  {% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
  {% breadcrumb_for 'catalog_item_list' %}Каталог{% endbreadcrumb_for %}
  {% breadcrumb_for 'seedlings:list' %}Саженцы{% endbreadcrumb_for %}
  {% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block content %}
  {% comment %} {% include 'common/listview/filters.html' %} {% endcomment %}
  <div class="container-fluid px-3 px-md-5">
  <form>
      <div class="row mb-4">
          {{ per_page }}
          {{ division_filter }}
      </div>
  </form>
  </div>

  <div class="container-fluid px-3 px-md-5">
    <div class="row">
      <div class="col-12">
        {% comment %} {% include 'common/listview/cards.html' %} {% endcomment %}

        {% if object_list %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 gx-4 gy-3">
            {% for object in object_list %}
                <div class="col">
                    <div class="card rounded-0 border-0 h-100">
                        {% if object.image_path %}
                            {% comment %} <a href="{{ object.url }}"><img class="card-img rounded-0 img-fluid" src="{{ object.image_path|thumbnail_url:'list' }}" alt="{{object.image_title}}" title="{{object.image_title}}"></a> {% endcomment %}
                            <a href="{{ object.image_path|thumbnail_url:'detail' }}" class="glightbox" data-glightbox="title:{{ object.name }}; description:Дата съемки: {{ object.date_shooting }};" aria-label="Увеличить"><img src="{{ object.image_path|thumbnail_url:'list' }}" class="card-img rounded-0 img-fluid" title="{{ object.image_title }}" alt="{{ object.image_title }}"></a>
                        {% else %}
                            <a href="{{ object.url }}">
                                {% include 'common/no_image_v.html' %}
                            </a>
                        {% endif %}
                        <div class="card-body px-1">
                            <p class="card-text"><a href="{{ object.url }}">{{ object.name }}</a><br>
                            Дата съемки: {{ object.date_shooting }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% else %}
            <div class="row">
                <div class="col-12">
                    {% include 'common/empty.html' %}
                </div>
            </div>  
        {% endif %}


        {% include 'pagination.html' %}
      </div>
    </div>
  </div>
{% endblock %}