carts/urls.py
from django.urls import path
from carts.views import CartView, cart_add, cart_remove, cart_update

app_name = 'carts'

urlpatterns = [
    path('', CartView.as_view(), name='index'),
    path('add/', cart_add, name='add'),
    path('update/', cart_update, name='update'),
    path('remove/', cart_remove, name='remove'),
]

profiles/urls.py
from django.urls import path
from profiles.views import (
    ProfileFavorites, ProfileIndex, ProfileOrderDetail, 
    ProfileOrderList, profile_update)


urlpatterns = (
    path('', ProfileIndex.as_view(), name='index'),
    path('update/', profile_update, name='update'),
    path('orders/', ProfileOrderList.as_view(), name='order_list'),
    path('order/<int:pk>/', ProfileOrderDetail.as_view(), name='order_detail'),
    path('favorites/', ProfileFavorites.as_view(), name='favorites'),
)

viride/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic import TemplateView
from django.shortcuts import render
from django.contrib.auth import views as auth_views
from django.views.defaults import page_not_found
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page
from catalog.sitemap import CatalogSitemap
from catalog.views import CatalogItemList
from conifers.sitemap import ConiferProductSitemap
from contacts.sitemap import ContactsSitemap
from contacts.views import contacts
from deciduous.sitemap import DecProductSitemap
from favorites.views import favorites
from fruits.sitemap import FruitProductSitemap
from index.sitemap import IndexSitemap
from index.views import index
from other.sitemap import OtherProductSitemap
from other.views import (
    BookProductDetail, BookProductList, RelatedProductDetail, RelatedProductList)
from perennials.sitemap import PerProductSitemap
from pricelist.sitemap import PriceListSitemap
from pricelist.view import price_list
from profiles.allauth.views import PersistLogoutView, RedirectedPasswordChangeView
from roses.sitemap import RoseProductSitemap
from sales.sitemap import SaleSitemap
from sales.views import sale
from search.views import SearchView


admin.site.site_header = admin.site.site_title = 'Питомник растений «Вириде»'


#--

sitemaps = {
    'index': IndexSitemap,
    'catalog': CatalogSitemap,
    'sale': SaleSitemap,
    'contacts': ContactsSitemap,
    'roses': RoseProductSitemap,
    'conifers': ConiferProductSitemap,
    'decs': DecProductSitemap,
    'fruits': FruitProductSitemap,
    'pers': PerProductSitemap,
    'other': OtherProductSitemap,
    # 'pricelist': PriceListSitemap,
}

# --

urlpatterns = [
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    path('admin/logout/', auth_views.LogoutView.as_view(next_page='/admin/login'), name='logout'),
    path('admin/', admin.site.urls),
    path("accounts/email/", page_not_found,
         kwargs={"exception": Exception("Page not Found")},),
    path('accounts/password/change/', RedirectedPasswordChangeView.as_view(),
         name="account_change_password"),

    # path('login/', PersistLoginView.as_view(), name='account_login'),
    path('accounts/logout/', PersistLogoutView.as_view(), name='account_logout'),

    # path('account/login/', RedirectView.as_view(permanent=True, url='/accounts/login/')), #seems allauth bug
    path('accounts/', include('allauth.urls')),
    path('accounts/profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),

    path('', index, name='index'),
    path('search/', SearchView.as_view(), name='search'),
    path('sale/', sale, name='sale_list'),
    path('price-list/', price_list, name='price_list_detail'),
    path('contacts/', contacts, name='contacts'),

    path('catalog/', CatalogItemList.as_view(), name="catalog_item_list"),
    # path('catalog/', TemplateView.as_view(
    #     template_name="catalog/index.html"), name="catalog_template"),

    path('catalog/conifers/', include(('conifers.urls','conifers'), namespace='conifers')),
    path('catalog/deciduous/',
         include(('deciduous.urls', 'deciduous'), namespace='decs')),
    path('catalog/fruits/', include(('fruits.urls', 'fruits'), namespace='fruits')),
    path('catalog/perennials/',
         include(('perennials.urls', 'perennials'), namespace='pers')),

    path('catalog/seedlings/',
         include(('seedlings.urls', 'seedlings'), namespace='seedlings')),
    
    path('catalog/roses/', include(('roses.urls', 'roses'), namespace='roses')),

    path('catalog/books/',
         BookProductList.as_view(), name='book_list'),
    path('catalog/books/<slug:slug>/',
         BookProductDetail.as_view(), name='book_detail'),

    path('catalog/related/',
         RelatedProductList.as_view(), name='related_list'),
    path('catalog/related/<slug:slug>/',
         RelatedProductDetail.as_view(), name='related_detail'),

    path('favorites/', favorites, name='favorites'),

    path('cart/', include(('carts.urls', 'carts'), namespace='carts')),
    path('order/', include(('orders.urls', 'orders'), namespace='orders')),

    path('privacy-policy/', TemplateView.as_view(
        template_name="privacy-policy/index.html"), name="p-p_template"),

    path('sitemap.xml', cache_page(86400, cache='sitemap')(sitemap), {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]

#--


def handler400(request, exception, template_name='errors/400.html'):
    response = render(request, template_name)
    response.status_code = 400
    return response


def handler403(request, exception, template_name='errors/403.html'):
    response = render(request, template_name)
    response.status_code = 403
    return response


def handler404(request, exception, template_name='errors/404.html'):
    response = render(request, template_name)
    response.status_code = 404
    return response


def handler500(request, template_name='errors/500.html'):
    response = render(request, template_name)
    response.status_code = 500
    return response

# --

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

    urlpatterns += [
        path('400/', TemplateView.as_view(template_name="errors/400.html")),
        path('403/', TemplateView.as_view(template_name="errors/403.html")),
        path('404/', TemplateView.as_view(template_name="errors/404.html")),
        path('500/', TemplateView.as_view(template_name="errors/500.html")),
    ]
        
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(r'/favicon.ico', document_root='static/favicon.ico')

favorites/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class Favorites(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        indexes = [
            models.Index(fields=["content_type", "object_id"]),
        ]
        verbose_name = 'избранное'
        verbose_name_plural = 'избранное'

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(
        'номер телефона', max_length=18, blank=True,)

    def __str__(self):
        return f"{self.user}"

    class Meta:
        verbose_name = 'профиль пользователь'
        verbose_name_plural = 'профили пользователей'


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if kwargs.get('raw'): #add for test, pass fixtures
        return
    if created:
        Profile.objects.create(user=instance)
        

profiles/forms.py
from django import forms
from django.core.validators import MinLengthValidator
from common.validators import LetterValidator, PhoneNumberValidator


class ProfileUpdateForm(forms.Form):
    required_css_class = 'required'
    
    def __init__(self, *args, **kwargs):
        #     self.extra_data = kwargs.pop('extra_data', None)
        super().__init__(*args, **kwargs)
    #     self.fields['username'].widget.attrs['class'] = 'form-control'
    #     self.fields['username'].initial = self.extra_data['username']
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Иван'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Иванов'

        self.fields['phone_number'].widget.attrs.update({
            'class': 'form-control',
            'data-phone-pattern': '',
            'placeholder': '+X (XXX) XXX-XX-XX',
        })

    first_name = forms.CharField(
        label='Имя:', required=False, validators=[LetterValidator, MinLengthValidator(2)],)

    last_name = forms.CharField(
        label='Фамилия:', required=False, validators=[LetterValidator, MinLengthValidator(2), ])

    phone_number = forms.CharField(
        label='Телефон:',
        required=False,
        validators=[PhoneNumberValidator,],)

favorites/views.py
import json
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponse
# from conifers.models import ConiferProduct
# from deciduous.models import DecProduct
# from fruits.models import FruitProduct
# from other.models import OtherProduct
# from perennials.models import PerProduct
# from roses.models import RoseProduct


# CT_ALLOWED = (ConiferProduct, DecProduct, FruitProduct,
#               PerProduct, RoseProduct, OtherProduct, )


@login_required
def favorites(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') != 'XMLHttpRequest':
        return HttpResponse(status=405)

    if request.GET.get('id') and (request.GET.get('id')).isdigit():
        object_id = request.GET.get('id')
    else:
        return HttpResponse(status=404)


    try:
        content_type = ContentType.objects.get_for_id(
            request.GET.get('ct_id'))
    except:
        return HttpResponse(status=404)

    # ct_allowed = ContentType.objects.get_for_models(*CT_ALLOWED)
    # if content_type.id not in [v.id for v in ct_allowed.values()]:
    #     return HttpResponse(status=405)

    try:
        content_type.get_object_for_this_type(pk=object_id)
    except:
        return HttpResponse(status=404)

    if request.user.favorites_set.filter(content_type=content_type, object_id=object_id):
        request.user.favorites_set.get(content_type=content_type,
                                       object_id=object_id).delete()
        state = False
    else:
        request.user.favorites_set.create(
            content_type=content_type, object_id=object_id)
        state = True

    response = {
        'state': state,
    }

    return HttpResponse(json.dumps(response))


# def favorites(request):
#     if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and request.user.is_authenticated:
#         user = request.user

#         app_label = request.GET.get('a', None)
#         if not app_label:
#             return HttpResponse(status=405)

#         model_name = request.GET.get('m', None)
#         if not model_name:
#             return HttpResponse(status=405)

#         if request.GET.get('id') and (request.GET.get('id')).isdigit():
#             object_id = request.GET.get('id')
#         else:
#             return HttpResponse(status=405)

#         try:
#             model = apps.get_model(app_label, model_name)
#         except LookupError:
#             return HttpResponse(status=405)

#         content_type = ContentType.objects.get_for_model(model)

#         try:
#             content_type.get_object_for_this_type(pk=object_id)
#         except model.DoesNotExist:
#             return HttpResponse(status=404)

#         if user.favorites_set.filter(content_type=content_type, object_id=object_id):
#             user.favorites_set.get(content_type=content_type,
#                                   object_id=object_id).delete()
#             state = False
#         else:
#             user.favorites_set.create(
#                 content_type=content_type, object_id=object_id)
#             state = True

#         response = {
#             'state': state,
#         }

#         return HttpResponse(json.dumps(response))

#     raise Http404

profiles/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import ListView, View, DetailView
from common.mixins import LoginRequiredMixin
from favorites.models import Favorites
from orders.models import Order, OrderItem
from profiles.forms import ProfileUpdateForm
from pure_pagination.mixins import PaginationMixin


class ProfileIndex(LoginRequiredMixin, View):
    template_name = 'profiles/index.html'

    def get(self, request, *args, **kwargs):
        return render(
            request=request,
            template_name=self.template_name
        )


@login_required
def profile_update(request):
    context = {}
    
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST)
        if form.is_valid():
            clean = form.cleaned_data
            user = User.objects.get(id=request.user.pk)
            user.profile.phone_number = clean['phone_number']
            user.profile.save()
            user.first_name = clean['first_name']
            user.last_name = clean['last_name']
            user.save()
            return redirect(reverse('profiles:index'))

        context['form'] = ProfileUpdateForm(request.POST)

    else:
        context['form'] = ProfileUpdateForm(initial={
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'phone_number': request.user.profile.phone_number,
        })

    return render(
        request,
        'profiles/update_form.html',
        context,
    )


class ProfileFavorites(LoginRequiredMixin, PaginationMixin, ListView):
    model = Favorites
    template_name = 'profiles/favorites_list.html'
    paginate_by = 8

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user) \
            .prefetch_related('content_object') \
            .prefetch_related('content_object__images')

        return qs


# class ProfileCart(PaginationMixin, LoginRequiredMixin, ListView):
#     model = Favorites
#     template_name = 'profiles/cart.html'
#     paginate_by = 8

#     def get_queryset(self):
#         qs = super().get_queryset()
#         qs = qs.filter(user=self.request.user) \
#             .prefetch_related('content_object')

#         return qs


class ProfileOrderList(LoginRequiredMixin, PaginationMixin, ListView):
    model = Order
    template_name = 'profiles/order_list.html'
    paginate_by = 12

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user) \
            .select_related('status') \
            .prefetch_related('order_items')
            # .prefetch_related('order_items__content_object')

        return qs


class ProfileOrderDetail(LoginRequiredMixin, DetailView):
    model = Order
    template_name = 'profiles/order_detail.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(user=self.request.user) \
            .select_related('status') \
            .prefetch_related('order_items')
            # .prefetch_related('order_items__content_object')

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        pk = self.kwargs.get(self.pk_url_kwarg)
        context['order_items'] = OrderItem.objects.filter(order_id=pk)

        return context

templates/profiles/favorites.html
{% extends "profiles/main.html" %}
{% load static humanize thumbnail django_bootstrap_breadcrumbs %}

{% block breadcrumb %}
{% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
{% breadcrumb_for 'profiles:index' %}Избранное{% endbreadcrumb_for %}
{% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block head %}
<title>Избранное</title>
{% endblock %}

{% block name %}
Избранное
{% endblock %}

{% block profile_content %}
{% if object_list %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
    {% for object in object_list %}
        {% with content_object=object.content_object %}
        {% if content_object.is_visible %}
            <div class="col">
                <div class="card rounded-0 border-0 h-100">
                    {% if content_object.get_image %}
                        <a href="{{ content_object.get_absolute_url }}"><img class="card-img rounded-0 img-fluid" src="{{ content_object.get_image.path|thumbnail_url:'list' }}" alt="{{ content_object.get_image.title }}" title="{{ content_object.get_image.title }}"></a>
                    {% else %}
                        <a href="{{ content_object.get_absolute_url }}">
                            {% include 'common/no_image_v.html' %}
                        </a>
                    {% endif %}

                    <div class="card-body px-1">
                        <p class="card-price">
                        {% if content_object.get_min_price %}
                            от {{ content_object.get_min_price }} руб.
                        {% else %}
                            нет в наличии
                        {%endif%}
                        </p>
                        <p class="card-text"><a href="{{ content_object.get_absolute_url }}">{{ content_object.name }}</a></p>
                    </div>
                </div>
            </div>
        {% endif %}
        {% endwith %}
    {% endfor %}
    </div>
{% else %}
    <div class="row">
        <div class="col-12">
            {% include 'common/empty.html' %}
        </div>
    </div>  
{% endif %}
{% include 'pagination.html' %}
{% endblock %}


templates/profiles/favorites_list.html
{% extends "profiles/main.html" %}
{% load static humanize thumbnail django_bootstrap_breadcrumbs %}

{% block breadcrumb %}
{% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
{% breadcrumb_for 'profiles:index' %}Избранное{% endbreadcrumb_for %}
{% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block head %}
<title>Избранное</title>
{% endblock %}

{% block name %}
Избранное
{% endblock %}

{% block profile_content %}
{% if object_list %}
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-3">
    {% for object in object_list %}
        {% with content_object=object.content_object %}
        {% if content_object.is_visible %}
            <div class="col">
                <div class="card rounded-0 border-0 h-100">
                    {% if content_object.get_image %}
                        <a href="{{ content_object.get_absolute_url }}"><img class="card-img rounded-0 img-fluid" src="{{ content_object.get_image.path|thumbnail_url:'list' }}" alt="{{ content_object.get_image.title }}" title="{{ content_object.get_image.title }}"></a>
                    {% else %}
                        <a href="{{ content_object.get_absolute_url }}">
                            {% include 'common/no_image_v.html' %}
                        </a>
                    {% endif %}

                    <div class="card-body px-1">
                        <p class="card-price">
                        {% if content_object.get_min_price %}
                            от {{ content_object.get_min_price }} руб.
                        {% else %}
                            нет в наличии
                        {%endif%}
                        </p>
                        <p class="card-text"><a href="{{ content_object.get_absolute_url }}">{{ content_object.name }}</a></p>
                    </div>
                </div>
            </div>
        {% endif %}
        {% endwith %}
    {% endfor %}
    </div>
{% else %}
    <div class="row">
        <div class="col-12">
            {% include 'common/empty.html' %}
        </div>
    </div>  
{% endif %}
{% include 'pagination.html' %}
{% endblock %}


templates/profiles/index.html
{% extends "profiles/main.html" %}
{% load humanize django_bootstrap_breadcrumbs %}

{% block breadcrumb %}
{% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
{% breadcrumb_for 'profiles:index' %}Профиль пользователя{% endbreadcrumb_for %}
{% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block head %}
<title>Профиль пользователя</title>
{% endblock %}

{% block name %}
Профиль пользователя
{% endblock %}

{% block profile_content %}
<div class="row">
    <div class="col-12 col-md-10 col-lg-7">
        <table class="table">
            <tr>
                <td>Адрес электронной почты:</td>
                <td>{{user.email}}</td>
            </tr>
            <tr>
                <td>Имя:</td>
                <td>{{user.first_name}}</td>
            </tr>
            <tr>
                <td>Фамилия:</td>
                <td>{{user.last_name}}</td>
            </tr>
            <tr>
                <td>Номер телефона:</td>
                <td>{{user.profile.phone_number}}</td>
            </tr>
            <tr>
                <td>Последний визит:</td>
                <td>{{user.last_login}}</td>
            </tr>
            <tr>
                <td>Дата регистрации:</td>
                <td>{{user.date_joined|naturalday:"j E Y"}}</td>
            </tr>
        </table>
        <a href="{% url 'profiles:update' %}">Изменить профиль</a><br>
        <a href="{% url 'account_change_password' %}">Изменить пароль</a>
    </div>
</div>
{% endblock %}

templates/profiles/main.html
{% extends "main.html" %}

{% block content %}
 <div class="container-fluid px-3 px-md-5 mb-3">
    <div class="row">
        <div class="col-12 col-md-3 mb-3 mb-md-0">
            <ul class="list-group">
                <li class="list-group-item">
                    <i class="far fa-user fa-fw"></i>
                    <a class="ms-1" href="{% url 'profiles:index' %}">Профиль</a>
                </li>
                <li class="list-group-item">
                    <i class="fas fa-box-open fa-fw"></i>
                    <a class="ms-1" href="{% url 'profiles:order_list' %}">Мои заказы</a>
                </li>
                <li class="list-group-item">
                    <i class="fas fa-heart fa-fw"></i>
                    <a class="ms-1" href="{% url 'profiles:favorites' %}">Избранное</a>
                </li>
                <li class="list-group-item">
                    <i class="fas fa-sign-out-alt fa-fw"></i>
                    <a class="ms-1" href="{% url 'account_logout' %}">Выйти</a>
                </li>
            </ul>
        </div>
        <div class="col-12 col-md-9">
            {% block profile_content %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

templates/profiles/order_detail.html
{% extends 'profiles/main.html' %}
{% load static humanize thumbnail django_bootstrap_breadcrumbs %}

{% block breadcrumb %}
  {% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
  {% breadcrumb_for 'profiles:order_list' %}Мои заказы{% endbreadcrumb_for %}
  {% breadcrumb_for 'profiles:order_detail' %}Заказ № {{ order.number }}{% endbreadcrumb_for %}
  {% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block head %}
  <title>Заказ № {{ order.number }}</title>
{% endblock %}

{% comment %} {% block name %}
  Заказ № {{ order.number }}
{% endblock %} {% endcomment %}

{% block profile_content %}
  <div class="row">
    <div class="col-12">
      {% comment %} {% if object_list %}
        <h2>Заказ № {{ order.number }} от {{ order.created_at|date:'DATE_FORMAT' }}</h2>
        <p>Статус заказа: {{order.status|lower}}</p>
        <div class="table-responsive">
        <table class="table table-striped table-responsive">
          <thead>
            <tr>
              <th scope="col">Наименование</th>
              <th scope="col">Кол-во</th>
              <th scope="col">Цена</th>
              <th scope="col">Сумма</th>
            </tr>
          </thead>
          <tbody>
            {% for order_item in object_list %}
              <tr>
                <td>{{ order_item.product }}</td>
                <td>{{ order_item.quantity }}</td>
                <td>&times; {{ order_item.price }} руб.</td>
                <td>= {{ order_item.total_price }} руб.</td>
              </tr>
            {% endfor %}
            <tr>
              <td colspan="4">
                <h6>Итого: {{ order.total_price }} руб.</h6>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
      {% else %}
        <div class="row">
          <div class="col-12">
            {% include 'common/empty.html' %}
          </div>
        </div>
      {% endif %} {% endcomment %}
        <h2>Заказ № {{ order.number }} от {{ order.created_at|date:'DATE_FORMAT' }}</h2>
        <p>Статус заказа: <em>{{order.status|lower}}</em></p>
        {% with cart_items=order_items cart=order %}
        {% include 'orders/cart.html' %}
        {% endwith %}
    </div>
  </div>
{% endblock %}

templates/profiles/order_list.html
{% extends 'profiles/main.html' %}
{% load static humanize thumbnail django_bootstrap_breadcrumbs %}

{% block breadcrumb %}
  {% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
  {% breadcrumb_for 'profiles:order_list' %}Мои заказы{% endbreadcrumb_for %}
  {% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block head %}
  <title>Мои заказы</title>
{% endblock %}

{% block name %}
  Мои заказы
{% endblock %}

{% block profile_content %}
  <div class="row">
    <div class="col-12">
      {% if object_list %}
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Номер заказа</th>
              <th scope="col">Дата</th>
              <th scope="col">Итого</th>
              <th scope="col" class="d-none d-sm-table-cell">Кол-во</th>
              <th scope="col" class="d-none d-sm-table-cell">Статус заказа</th>
            </tr>
          </thead>
          <tbody>
            {% for order in object_list %}
              <tr>
                <td>
                  № <a href="{% url 'profiles:order_detail' order.id %}">{{ order.number }}</a>
                </td>
                <td><span class="d-none d-md-inline">{{ order.created_at|date }}</span> <span class="d-inline d-md-none text-lowercase">{{ order.created_at|date:"d N Y" }}&nbsp;г.</span></td>
                <td>{{ order.total_price }} руб.</td>
                <td class="d-none d-sm-table-cell">{{ order.total_quantity }}</td>
                <td class="d-none d-sm-table-cell">{{ order.status }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      {% else %}
        <div class="row">
          <div class="col-12">
            <p>Вы еще не сделали ни одного заказа.</p>
          </div>
        </div>
      {% endif %}

      {% include 'pagination.html' %}
    </div>
  </div>
{% endblock %}

templates/profiles/update.html
{% extends 'profiles/main.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block head %}
<title>Изменить профиль пользователя</title>
{% endblock %}

{% block breadcrumb %}
{% breadcrumb_for '/' %}<i class="fas fa-home"></i>{% endbreadcrumb_for %}
{% breadcrumb_for 'profiles:index' %}Профиль пользователя{% endbreadcrumb_for %}
{% breadcrumb_for 'profiles:update' %}Изменить профиль пользователя{% endbreadcrumb_for %}
{% render_breadcrumbs 'breadcrumb.html' %}
{% endblock %}

{% block name %}
Изменить профиль пользователя
{% endblock %}

{% block profile_content %}
{% comment %} {% if form.errors %}
    <div class="alert alert-danger">Пожалуйста исправьте ошибки
        <a class="close" data-dismiss="alert">×</a>
    </div>
{% endif %} {% endcomment %}

{% comment %} {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error }}
            <a class="close" data-dismiss="alert">×</a>
        </div>
    {% endfor %}
{% endif %} {% endcomment %}
<div class="row">
    <div class="col-12 col-md-10 col-lg-7">
        <form method="POST">{% csrf_token %}
        {% for field in form %}
            <div class="mb-3 {% if field.errors %}has-error{% endif %}">
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %}required{% endif %}">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <span class="text-danger">{{ field.errors.as_text }}</span>
                {% endif %}
            </div>
        {% endfor %}
            <button type="submit" class="btn btn-primary col-lg-3">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}


{% comment %} <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email address</label>
  <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
</div>
<div class="mb-3">
  <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
  <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
</div> {% endcomment %}